# Generated by Django 5.0.1 on 2024-01-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musian',
            new_name='Musician',
        ),
    ]
